typography_spectrum: 0.8622010256439484
color:
  saturation: 0.5073227832153772
  brandStrength: 0.16827608921906292
  rhythmicContrast: 0.2740326168839036
  brandColors:
    - '#FFFFFF'
    - '#695D48'
    - '#FA7141'
    - '#128475'
    - '#6AB5AB'
  lightness: 0.9203910960357563
github: true
layout_spectrum: 0.04201026865022976
analytics:
  google: UA-45030951-11
  twitter: nvmox
author:
  name: Nicolai Kobiakov
  email: nkobliakov@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/867841fa-ff75-4d0e-903e-177d4b632463.png
name: _
navigation:
  - name: “Senior New Europe” Project Development Logic.
    id: b0d0a460-b124-46ca-833a-ead4bda0ad0f
    type: content
  - name: Strategic basis for the “Senior New Europe” project
    id: 7e25a2a8-ebd0-4335-835e-7c8e94d6446f
    type: content
  - name: Parameters of the “Senior New Europe” project.
    id: 45f12b86-0263-40d0-8a0b-87255b454055
    type: content
  - name: 'Facilities, the types of development'
    id: c64157a5-1753-4cc7-a279-870fb95ccac7
    type: content
  - name: 'Founders: Kobliakov'
    id: 1f41bce3-fd7f-4c81-8b9e-ed75daaccdd2
    type: content
  - name: Polish Senior Care perspectives. Some figures and conclusions.
    id: 96d4e630-140b-47e7-a1f1-73a80ca38912
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fcc57bc6-7d4a-4755-a47e-703a21c1de42.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Senior Group
content: []
description: >-
  We assist seniors and persons with limited mobility in leading full,
  comfortable lives in our residences
purpose:
  - type: external
    url: >-
      https://docs.google.com/document/d/1Y1xBJYHFGXJurNYSRm8U0WJRZuNk-prsYsqiwKbP7G8/edit?usp=sharing
    label: '"Senior Baltic" Dossier'
  - type: contact
    url: 'mailto:kobliakov@senior-group.fr'
    label: Contact us
